Metrics Webapp
Piercel2022/metrics-webapp pull request #1
Opened 2022-09-10 19:52 UTC by Piercel2022

This react capstone is about building a mobile web application to check a list of metrics (numeric values) that you will create making use of React and Redux. This webapp is based on the Financial Modeling Prep  and  is the most accurate financial data API. Financial statements  are updated in real time, every statements is audited, standardized, and up to date. 

Testing requirements

    Create unit tests for pure functions in your Redux code.
    Create integration tests for your application using the React Testing Library.
        You may need to mock the access to the API, so that your tests don't send actual requests.
        You may need to mock the connection to the Redux Store.

Technical requirements

    The project is a single-page application (SPA) built with React and Redux.
    The data retrieved from the API should is stored in the Redux store.
     The data that I retrieve are filtered from the API using a Filter stateless component.
    Every page (the main page and the pages for each item)  have a unique route within the SPA.
    The project is deployed and accessible online (there is a link to the online version of the app in the README file).
![Stock](https://user-images.githubusercontent.com/98626003/189499687-13339bc1-2017-4dfb-b446-d7f64f363222.png)

2022-09-10 21:59 UTC, AmaduKamara requested changes
# Status: Required Changes ♻️♻️♻️ 

Hi @Piercel2022,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ You used Gitflow correctly
✅ No linter error
✅ Good commit messages
✅ PR description is okay
✅ App is beautifully designed and interactive. 👍 

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly record a video presenting your project in professional English as required in the project requirements. It is recommended you use Loom to record the video. While recording your presentation, please take note of the points below:
- Record a video presenting the features of the project.
- The maximum length of the video is 5 minutes.
- The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
- The video contains a demo of the project, highlighting all the project features.
- The video contains a highlight about a piece of the code you find interesting or proud of making.

- [ ] It would be nice also for you to add the link of the video presentation to your PR or your README file so the next reviewer can be able to access it. 👍 

- [ ] Kindly give credit to the original creator of the design you used as inspiration to develop this project. 
- The README contains an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).The README contains an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

- [ ] Also, you are to deploy the project to either Netlify or Heroku and add the deployed app's link on to your README file. I trust you can do that 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-10 21:59 UTC, AmaduKamara commented on src/App.js
> +    // eslint-disable-next-line
- [ ] Kindly remove the ESLint disable here. ESLint is there to help you write better code and disabling it defies its purpose. Please fix the linter check on this part 👍

2022-09-10 21:59 UTC, AmaduKamara commented on src/__tests__/Components.react.test.js
> +  });
- [ ] The test on rendering the Card component is failing. Kindly fix that

![image](https://user-images.githubusercontent.com/50941074/189502673-bb024b8e-ffe4-45dd-834b-3325d30aa27c.png)

2022-09-10 21:59 UTC, AmaduKamara commented on src/__tests__/Components.react.test.js
> +
- [ ] The test on rendering the Details Card component is failing. Kindly fix that

![image](https://user-images.githubusercontent.com/50941074/189502714-8d3cd988-133c-440f-b858-76b8b701f398.png)

2022-09-10 21:59 UTC, AmaduKamara commented on src/__tests__/Components.react.test.js
> +});
- [ ] The test on rendering the Header component is failing. Kindly fix that

![image](https://user-images.githubusercontent.com/50941074/189502768-b612882a-e0b0-4d83-93fa-4090edb1a422.png)

2022-09-10 21:59 UTC, AmaduKamara commented on src/__tests__/Components.react.test.js
> +  });
The test on rendering the Hero component is failing. Kindly fix that
![image](https://user-images.githubusercontent.com/50941074/189502795-563e2a65-9d32-4254-ab3d-a3906dd3b22a.png)

2022-09-10 21:59 UTC, AmaduKamara commented on src/__tests__/Components.react.test.js
> +  });
- [ ] The test on rendering the SearchBar component is failing. Kindly fix that

![image](https://user-images.githubusercontent.com/50941074/189502810-43050921-cc64-468b-b911-855c63fd1dbb.png)

2022-09-14 16:59 UTC, Nemwel-Boniface requested changes
## Hello @Piercel2022       :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job addressing some of the changes that were requested by a previous reviewer :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] I have made sure to recheck and I confirm that you have not attributed the original creator of the provided design in your README.md file. Kindly recheck the [previous reviewer's](https://github.com/Piercel2022/metrics-webapp/pull/1#pullrequestreview-1103178736) comment he made sure to point this one out to you.

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 21:20 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @Piercel2022, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://camo.githubusercontent.com/f181708ef1a4a773db8464e77479f28ed4dae506d4d8da5c19f44c8e00d31232/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f594b646d3931584f4e4c5461772f67697068792d646f776e73697a65642d6d656469756d2e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-09-14 21:22 UTC, merged